### ISSUE TITLE
CSS Injector

### ISSUE THREAD

**Issue by whippingdot** [replit-discord/repl-it-electron#138]
I use a CSS injector for making repl.it look nice. This isn't a web app, so I can't use the CSS Injector. Can you make an option for injecting your own CSS into the app? I would use @frissyn's Reflux, but that has a white page on the post pages. BTW the code for my injected CSS is this:
```CSS
.line-numbers {
    color: var(--color-primary-1) !important;
}

.replit-ui-theme-root {
    --color-background-1: #141414 !important;
    --color-background-2: #070707 !important;
    --color-background-3: #1D1E20 !important;
    --color-background-4: #141414 !important;
    --color-control-1: #1D1E20 !important;
    --color-control-2: #1D1E20 !important;
    --color-control-3: #1D1E20 !important;
    --color-border: #141414 !important;
    --color-foreground-1: #C9CBCF !important;
    --color-foreground-2: #B3B6BC !important;
    --color-foreground-3: #9FA2A8 !important;
    --color-foreground-4: #233329 !important;
    --color-primary-1: #2D07DA !important;
    --color-primary-2: #3C12F8 !important;
    --color-primary-3: #5C39F9 !important;
    --color-primary-4: #2D07DA !important;
}

.monaco-editor, .monaco-editor-background, .monaco-editor .inputarea.ime-input, .monaco-editor .margin {
    background-color: #090128 !important;
}

.monaco-editor .margin-view-overlays .current-line-margin, .current-line {
    background-color: #0D023C !important;
}

.jsx-3971054001.content, p, .jsx-4279741890 {
    background-color: var(--color-background-2) !important;
    color: #B3B6BC !important;
}

.jsx-3414412928 {
    background-color: var(--color-background-1) !important;
}

.toggle-bar {
    background-color: var(--color-foreground-2) !important;
}

a.jsx-330798097, .jsx-801033477, a.jsx-56292044 {
    color: #29339B !important;
}

.jsx-467725132 {
    background-color: var(--color-background-3) !important;
}

.jsx-2906438576, .jsx-986859180, .jsx-918008940  {
    background-color: var(--color-background-3) !important;
}

.interactive.jsx-2106077415:hover {
    border-color: var(--color-background-4) !important;
}

.jsx-3414412928.sidebar-layout-header-toggle-alert {
    background-color: var(--color-primary-1) !important;
}
```
